### ISSUE TITLE
Transfers are confusing

### ISSUE THREAD

**Issue by elaynepelz** [jordanbrown0/reg3#202]
Transfers should say "Transfer from" instead of "General"

**Comment by jordanbrown0** [comment]
At that point you are giving the information about the transfer-to person.  The page main title already says "Transfer", but could easily say "Transfer To".

One of the other things that should probably be improved there is that it should wipe at least the name and perhaps the address, since you probably need new ones for the transfer-to person.

**Comment by jordanbrown0** [comment]
Seems fixed.
